### ISSUE TITLE
Alt Format Not Changing

### ISSUE THREAD

**Issue by vitorpena** [savannabits/filament-flatpickr#10]
Hi,

I noticed that the alt format wasn't being changed, so I tinkered a bit and explored that we needed to tweak a couple of lines of code.

In file: flatpickr.blade.php please add: "altInput" => $isAltInput(), after line 3.

In file dist/datepicker.js please change line 16 to "altFormat: attribs.altFormat,"

That should do it. Thanks for making this component I really appreciate it!

**Comment by coolsam726** [comment]
Hi @vitorpena,
Thank you for taking your time to explore the solution to your issue. Could you kindly make the changes in a fork and submit a Pull Request? I would be glad to merge it.

Thanks!

**Comment by coolsam726** [comment]
Fixed in #27

**Comment by coolsam726** [comment]
Fixed in #27
