### ISSUE TITLE
Range picker doesn't seem to work.

### ISSUE THREAD

**Issue by 0liverdam** [savannabits/filament-flatpickr#11]
A `Carbon\Exceptions\InvalidFormatException` is thrown when submitting a range picker.
This seems to happen because `dehydrateStateUsing()` tries to parse the state with `Carbon`. Since the state contains 2 dates the parsing fails.

The same happens when using `default()`, but this time `afterStateHydrated()` fails with the same error.

**Comment by wit3** [comment]
Bug confirmed, any ideas to fix?

**Comment by coolsam726** [comment]
Fixed in #27
