### ISSUE TITLE
Datepickr does not work and only shows undefined

### ISSUE THREAD

**Issue by tiagofcp** [savannabits/filament-flatpickr#23]
Attached 2 screenshots, one showing the field the other with the errors on console

<img width="436" alt="Screenshot 2023-05-29 at 17 34 28" src="https://github.com/savannabits/filament-flatpickr/assets/12100048/634f2baa-cb60-4b08-9bd1-bcd91574f781">

<img width="1790" alt="Screenshot 2023-05-29 at 17 32 58" src="https://github.com/savannabits/filament-flatpickr/assets/12100048/18cc1000-1dd2-47ae-a197-033d8f2025da">

**Comment by coolsam726** [comment]
Fixed in #27
