### ISSUE TITLE
Request: ->disabledDates([]) to match official filament date time picker field

### ISSUE THREAD

**Issue by ziming** [savannabits/filament-flatpickr#24]
It will be nice if this package can support disabled dates like the official filament datetime picker field.

Flatpickr does support this

https://flatpickr.js.org/examples/#disabling-dates

**Comment by Haggai-Mac** [comment]
@ziming You can pass it like this:
`Flatpickr::make('date')->config(['disable' => ["2025-01-30", "2025-02-21", "2025-03-08"]])`

**Comment by coolsam726** [comment]
The feature has been added in #27. Use either **->enabledDates()** or **->disabledDates()**

**Comment by ziming** [comment]
Thank you, does this package plan to support filament v3 in the near future?

If not, that is fine too

Thank you
