### ISSUE TITLE
[Bug]: Datetime Picker field submits Null

### ISSUE THREAD

**Issue by chrisreedio** [savannabits/filament-flatpickr#35]
### What happened?

To put the form component in my form and be able to pick a date and have that submitted to my livewire form handler.

`Flatpickr::make('my_date_field'),`

If I `dd` out the submitted data, the field is there but it's always null.

### How to reproduce the bug

I added a simple flatpicker form component to a form with no additional options. 

I picked a date.

The submitted field is always null.

### Package Version

3.0.0

### PHP Version

8.1

### Laravel Version

10

### Which operating systems does with happen with?

macOS, Windows, Linux

### Notes

The normal DatePicker works so it does appear that there is an issue with this plugin. 

Looking forward to helping bring a resolution to this. Let me know if there is any more information I can provide.

Thanks!

**Comment by coolsam726** [comment]
Thanks, @chrisreedio for catching this. The bug has been fixed in v3.0.1.

**Comment by chrisreedio** [comment]
Tested and it works! Super fast turn around!

Thanks so much! 🚀
