### ISSUE TITLE
[Bug]: Filament v3: Once date is selected it refreshes the state of input to empty

### ISSUE THREAD

**Issue by nlvrendell** [savannabits/filament-flatpickr#45]
### What happened?

Newly installed on filament version 3. Once input data is selected it refreshes the state of input to empty. Making the selected date gone. 

Loom: https://www.loom.com/share/e5190cf44a8e449b80ad5b8e1dca07a0?sid=8f354c94-a4a9-4af0-ac40-5731ed3100f5

### How to reproduce the bug

Filament version 3.
Custom page  with form

### Package Version

3.0

### PHP Version

8.1

### Laravel Version

10

### Which operating systems does with happen with?

Windows

**Comment by wbzy05** [comment]
i have the same problem
