### ISSUE TITLE
[Bug]: syntax error, unexpected token "|", expecting ")"

### ISSUE THREAD

**Issue by flashmediasolutions** [savannabits/filament-flatpickr#57]
### What happened?

syntax error, unexpected token "|", expecting ")"

### How to reproduce the bug

Seen on initial load.

### Package Version

3.1.0

### PHP Version

8.2.0

### Laravel Version

10

### Notes

In Flatpickr.php - $minDate|Closure is causing the syntax error.
```
public function minDate(Carbon|string|null $minDate|Closure): static
    {
        $this->minDate = $minDate ? Carbon::parse($minDate) : $minDate;

        return $this;
    }
```

**Comment by crgAdrian** [comment]
same here

**Comment by hyphen81** [comment]
same..

**Comment by AhmadFida2** [comment]
The Closure portion should be removed or it should be evaluated in the function and placed before variable.

**Comment by aeq-dev** [comment]
same here

**Comment by ionutrobert** [comment]
same here.

**Comment by crgAdrian** [comment]
any updates?

**Comment by Emmanuel71git** [comment]
same problem here with following code in AppServiceProvider:

Flatpickr::macro('customFlatpickr', function () {
            return $this->enableSeconds(false)
                ->dateFormat("d-m-Y H:i")->use24hr(true)->theme(FlatpickrTheme::AIRBNB);
        });

**Comment by LucasVieira2902** [comment]
any updates ? 
same problem here

![image](https://github.com/savannabits/filament-flatpickr/assets/66380573/57c4b7aa-85ee-4c0b-8e7b-082e322d4935)

**Comment by mikevcube** [comment]
@coolsam726 can you release?

**Comment by zailmer30** [comment]
Have you found any solution for this error?

**Comment by aeq-dev** [comment]
As we can see, the package owner has a bad experience regarding PRs and issues !!

**Comment by aeq-dev** [comment]
@divdax This doesn't concern you, so you can keep your reply to yourself

**Comment by Emmanuel71git** [comment]
Thank you @hyphen81 I didn't know this and I'll try it out. it seems like a nice workaround for now.
At the risk of getting yelled at... I've been waiting several weeks now for a release. And yes, I want to applaud the work and effort for bringing flatpickr to filament very much. But I feel respect has to go both ways. A short message from the maintainer about when a release could be expected would have been nice too, but maybe that was not possible for some reason.
So anyway, I'm just glad I learned something new through this.

**Comment by ChWebTech** [comment]
Same here.

syntax error, unexpected token "|", expecting ")"

**Comment by kurob1993** [comment]
same issue

**Comment by brunocascio** [comment]
Until a new release is published, it can be installed by using:

`composer require coolsam/flatpickr:3.x-dev`
